# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-06-26 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('picture', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('staging', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True, default='')),
                ('pro_pic', models.TextField(null=True)),
                ('active', models.BooleanField(default=True)),
                ('email', models.TextField()),
                ('phone', models.TextField()),
                ('year', models.CharField(choices=[('Year 1', 'YEAR_1'), ('Year 2', 'YEAR_2'), ('Year 3', 'YEAR_3'), ('Year 4', 'YEAR_4'), ('Graduated', 'GRADUATED'), ('Master', 'MASTER'), ('Other', 'OTHER')], default='Other', max_length=16)),
                ('section', models.CharField(choices=[('Alto', 'ALTO'), ('Bass', 'BASS'), ('Soprano', 'SOPRANO'), ('Tenor', 'TENOR'), ('Other', 'OTHER')], default='Other', max_length=16)),
                ('staging', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('staging', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='roles',
            field=models.ManyToManyField(to='main.Role'),
        ),
    ]
